### ISSUE TITLE
Facing issue when running

### ISSUE THREAD

**Issue by sravanithamatamqualbrain** [ahmettugur/ReactAndReduxWithAspNetCore2WebApi#1]
Hi Team,

I installed RabbitMQ and When i am running OnlineStore application I am getting some exception. I.e, 'HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed)'.

Is there any thing that i need to do in configurations and am i missed anything when i am installing RabbitMQ?

Please give the proper steps to run this application.

Thank you
Sravani Thamatam

**Comment by humayunkhan** [comment]
There are a couple of changes needed in the source code for the application to work as expected:

- In the OnlineStore.Api -> Startup.cs -> Configure( ) method, the UseEndPoints( ) method needs an extra line of code to Map the SignalR Hub:

app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<ProductHub>("/producthub");
                endpoints.MapControllers();
            });

- In OnlineStore.MQService -> appsettings.json change the "HubConnection" setting as following:
"HubConnection": "http://localhost:2519/producthub"

- In the OnlineStoreReact/src/components/product/product-detail.js change the hub connection port number:
const hubConnection = new signalR.HubConnectionBuilder()
      .withUrl("http://localhost:2519/producthub")
      .configureLogging(signalR.LogLevel.Information)
      .build();

- Also, you need to run the projects in the following order:
OnlineStore.API
OnlineStore.GrpcService
OnlineStore.MQService
In the end the React Web portal

With all the above changes in place, I was able to run this.

**Comment by sravanithamatamqualbrain** [comment]
I made all the changes that you are mentioned above. 
Now I am able to run the MQService and also able to run React page as well.

After struggling for many days, finally i am able to run this application with the help of your investigation on this application code. Thank you very much @humayunkhan .
